baseURL = 'https://anna142204.github.io/labveilletech/'
languageCode = 'fr-fr'
title = 'Anna Tranchida'
theme = 'stack'

# --- Configuration du Markup (Pour autoriser le HTML) ---
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      noClasses = false
      codeFences = true
      guessSyntax = true
      lineNos = true
      tabWidth = 4

# --- Services (Commentaires, Analytics...) ---
[services]
  [services.disqus]
    shortname = "hugo-theme-stack" # Changez ceci si vous avez un compte Disqus

# --- Param√®tres du site ---
[params]
  mainSections = ["post"]
  featuredImageField = "image"
  rssFullContent = true
  favicon = "/favicon.ico" # Si vous en avez un dans static/favicon.ico

  [params.footer]
    since = 2026
    customText = "Laboratoire de veille technologique"

  # --- Barre Lat√©rale ---
  [params.sidebar]
    emoji = "üìö"
    subtitle = "√âtudiante en Ing√©nierie des M√©dias"


  # --- R√©glages des Articles ---
  [params.article]
    math = false
    toc = true
    readingTime = false
    [params.article.license]
      enabled = true
      default = "Licensed under CC BY-NC-SA 4.0"

  # --- Commentaires ---
  [params.comments]
    enabled = false # Mettez √† true si vous configurez Disqus plus haut
    provider = "disqus"

  # --- Widgets (Colonne de droite ou bas de page) ---
  [params.widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } }
    ]
    page = [
        { type = "toc" }
    ]

# --- Menus ---
[menu]
  # Menu "Social" (Ic√¥nes en bas √† gauche)
  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/anna142204"
    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "www.linkedin.com/in/anna-tranchida"
    [menu.social.params]
      icon = "linkedin"

   [[menu.social]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "https://anna.tranchida.ch"
    [menu.social.params]
      icon = "globe"

# --- Articles li√©s ---
[related]
  includeNewer = true
  threshold = 60
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 200